login:
    path: /login
    defaults: { _controller: AppBundle:Page:landing }

logout:
    path: /logout
    defaults: { _controller: AppBundle:Page:landing }

login_check:
    path: /login_check

default:
    path:  /
    defaults: { _controller: AppBundle:Page:landing }
    schemes:  [https]

home:
    path:  /home
    defaults: { _controller: AppBundle:Page:landing }
    schemes:  [https]

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

sustain_user:
    resource: "@SustainUserBundle/Controller/"
    type:     annotation
    prefix:   /





