# app/config/security.yml
security:
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            logout:
                path:   /logout
                target: /
            trusted_sso:
                manager: admin_sso
                create_users: false
                login_action: false
                logout_action: false
                login_path: /login
                check_path: /login
            provider: fos_userbundle
            anonymous:    true
            switch_user: true

    access_control:
        - { path: ^/user/[0-9]*/edit, role: ROLE_USER, requires_channel: https  }
        - { path: edit$, role: ROLE_ADMIN, requires_channel: https  }
        - { path: new$, role: ROLE_ADMIN, requires_channel: https  }
        - { path: delete$, role: ROLE_ADMIN, requires_channel: https  }
        - { path: create$, role: ROLE_ADMIN, requires_channel: https  }
        - { path: update$, role: ROLE_ADMIN, requires_channel: https  }
        - { path: ^/tag/, role: ROLE_ADMIN, requires_channel: https  }
        - { path: ^/section/, role: ROLE_ADMIN, requires_channel: https  }
        - { path: ^/category/, role: ROLE_ADMIN, requires_channel: https  }




    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN     
        