# app/config/security.yml
security:
    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                csrf_provider: form.csrf_provider
                default_target_path: /user/profile
            logout:
                path:   /logout
                target: /login
            anonymous:    true
            switch_user: true

    access_control:
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/module/, role: ROLE_USER }
        - { path: ^/file/, role: ROLE_USER }
        - { path: ^/tag/, role: ROLE_USER }
        - { path: ^/user/, role: ROLE_USER }



    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN     
        