# app/config/security.yml
security:

    access_control:

        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/home, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/user/[0-9]*/edit, role: ROLE_USER }
        - { path: edit$, role: ROLE_ADMIN }
        - { path: new$, role: ROLE_ADMIN }
        - { path: delete$, role: ROLE_ADMIN }
        - { path: create$, role: ROLE_ADMIN }
        - { path: update$, role: ROLE_ADMIN }
        - { path: ^/tag/, role: ROLE_ADMIN }
        - { path: ^/category/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }