services:
    sso_user_provider:
        class: AppBundle\Security\SSOUserProvider
        arguments:
            - '@fos_user.user_manager'
            - '@doctrine.orm.entity_manager'
            - '@fos_user.util.token_generator'