<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    /**
     * Find activities by tag
     */
    public function activitiesByTag($tag)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM AppBundle:Activity a JOIN  a.tags t WHERE t.id = ?1 ')
            ->setParameter('1',$tag)->getResult();
    }
}
