<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{

    /**
     * Find activities by tag
     * @return Activity
     */
    public function activitiesByTag($tag)
    {
        return $this->createQueryBuilder('act')
            ->addSelect('tags')
            ->leftJoin('act.tags','tags')
            ->andWhere('tags.id = :tag')
            ->setParameter('tag',$tag)
            ->getQuery()
            ->getResult();
    }
}
