<?php

namespace Sustain\AppBundle\Entity;

/**
 * CarouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarouselRepository extends \Doctrine\ORM\EntityRepository
{
}
