<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * Find all upcoming events sorted by start
     *
     * @return Event
     */
    public function eventByDate() {
        $start = date("Y-m-d");
        $events = $this->createQueryBuilder('e')
            ->andWhere('e.start >= :start')
            ->orderBy('e.start', 'ASC')
            ->setParameter('start',$start)
            ->getQuery()
            ->getResult();
        return $events;
    }
}
