<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    /**
     * Find files by tag
     */
    public function filesByTag($tag)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT f FROM AppBundle:File f JOIN  f.tags t WHERE t.id = ?1 ')
            ->setParameter('1',$tag)->getResult();
    }
}
