<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapRepository extends EntityRepository
{
    public function map_json()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT m.lat as latitude, m.lng as longitude, m.title, m.description as content FROM AppBundle:Map m WHERE m.map = 1 ')->getResult();
    }
}
