<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends EntityRepository
{

    /**
     * Find modules by tag
     * @return Module
     */
    public function modulesByTag($tag)
    {
        return $this->createQueryBuilder('m')
            ->leftJoin('m.tags', 't')
            ->addSelect('t')
            ->andWhere('t.id = :tag')
            ->setParameter('tag', $tag)
            ->getQuery()
            ->getResult();
    }
}
