<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ObjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectiveRepository extends EntityRepository
{

    /**
     * Find objectives by tag
     * @return Objective
     */
    public function objectivesByTag($tag)
    {
        return $this->createQueryBuilder('o')
            ->leftJoin('o.tags', 't')
            ->andWhere('t.id = :tag')
            ->addSelect('t')
            ->setParameter('tag', $tag)
            ->getQuery()
            ->getResult();
    }
}
