<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OpportunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportunityRepository extends EntityRepository
{

    public function opportunitiesSorted($type) {
        $opportunities = $this->createQueryBuilder('o')
            ->orderBy('o.title','ASC')
            ->andWhere('o.type = :type')
            ->setParameter('type', $type)
            ->getQuery()
            ->getResult();
        return $opportunities;
    }
}
