<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * Find pages for homepage
     * @return Page
     */
    public function findHome()
    {
        return $this->createQueryBuilder('p')
            ->andWhere('p.homepage = :switch')
            ->setParameter('switch',true)
            ->orderBy('p.sortorder','ASC')
            ->getQuery()
            ->getResult();
    }
}
