<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends EntityRepository
{

    /**
     * Find sections to display
     * @return Section
     */
    public function findSorted() {

        return $this->createQueryBuilder('s')
          ->where('s.display=:display')
          ->addOrderBy('s.name','ASC')
          ->setParameter('display', true)
          ->getQuery()
          ->getResult();

    }
}
