<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
  /**
 * Find files by tag
 */
    public function sortedTags()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM AppBundle:Tag t Order By t.color')
            ->getResult();
    }
}
