<?php

namespace Sustain\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    /**
     * Find tags sorted
     * @return Tag
     */
    public function sortedTags()
    {
        return $this->createQueryBuilder('t')
            ->orderBy('t.color', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
