<?php

namespace Sustain\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     *
     * @return User
     */
    public function findPublic()
    {
        return $this->createQueryBuilder('u')
            ->andWhere('u.public = :public')
            ->andWhere('u.role >= :role')
            ->setParameter('public', '0')
            ->setParameter('role', '2')
            ->addOrderBy('u.lastname', 'ASC')
            ->getQuery()
            ->getResult()
            ;
    }
}
